#LingDouLuo Configuration
#Fri Dec 26 02:14:12 GMT+08:00 2025
key_down=83
key_jump=75
key_left=65
key_right=68
key_shoot=74
key_up=87
key_weapon_switch=85
master_volume=1.0
music_volume=0.8
sfx_volume=1.0
